// GENERATED FROM src/docs/DADOS CARCERES-v2.xlsx
import { Linha } from "@/types/cadastro"

export const LINHAS: Linha[] = [
{
    id: 1,
    nome: "VIDA NOVA/LARANJEIRA/FURNAS",
    motorista: "ADEMAR CARVALHO SILVA",
    telefone: "65 9948-5799",
    arquivoGPX: "01.gpx",
    nucleoId: 4,
    turno: "MATUTINO",
},
{
    id: 2,
    nome: "VIDA NOVA/LARANJEIRA/FURNAS",
    motorista: "ADEMAR CARVALHO SILVA",
    telefone: "65 9948-5799",
    arquivoGPX: "02.gpx",
    nucleoId: 4,
    turno: "VESPERTINO",
},
{
    id: 3,
    nome: "ALEGRIA 2/AGUA BOA",
    motorista: "ADRIELTON NASCIMENTO CARVALHO",
    telefone: "65 9957-3628",
    arquivoGPX: "03.gpx",
    nucleoId: 2,
    turno: "MATUTINO",
},
{
    id: 4,
    nome: "BARRANQUEIRA 2",
    motorista: "ALMERINDO DUARTE DA SILVA",
    telefone: "65 9665-8012",
    arquivoGPX: "04.gpx",
    nucleoId: 2,
    turno: "MATUTINO",
},
{
    id: 5,
    nome: "BOCAINA DO CASCAVEL",
    motorista: "ALOISIO DA CONCEICAO LOPES MARTINS VIANA",
    telefone: "65 9965-2410",
    arquivoGPX: "05.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 6,
    nome: "SANTA RITA/SANTA MARIA",
    motorista: "ANDRE LUIZ VILAS BOAS DO ESPIRITO SANTO",
    telefone: "65 9817-6721",
    arquivoGPX: "06.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 7,
    nome: "BARREIRO PRETO",
    motorista: "ADEMILCO SOUZA MILAS",
    telefone: "65 99977-7697",
    arquivoGPX: "07.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 8,
    nome: "BOA ESPERANCA/SAO JOSE/BOM JARDIM",
    motorista: "ODAIR CAMACHO DE SOUZA",
    telefone: "65 99636-2859",
    arquivoGPX: "08.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 9,
    nome: "BOM JARDIM/BR",
    motorista: "JOILSON FELIX MACEDO",
    telefone: "65 99946-0417",
    arquivoGPX: "09.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 10,
    nome: "CAICARA/LIMAO",
    motorista: "ELYSSON VIDAL GUILHER",
    telefone: "65 98419-7041",
    arquivoGPX: "10.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 11,
    nome: "CAICARA/MINUANO/ROTA DAS AGUAS",
    motorista: "ALISON RIBEIRO FELIX",
    telefone: "65 99609-0109",
    arquivoGPX: "11.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 12,
    nome: "VALE DO MANGAVAL",
    motorista: "CESAR OLIVEIRA QUEROZ",
    telefone: "65 8461-9301",
    arquivoGPX: "12.gpx",
    nucleoId: 7,
    turno: "MATUTINO",
},
{
    id: 13,
    nome: "VALE DO MANGAVAL",
    motorista: "CESAR OLIVEIRA QUEROZ",
    telefone: "65 8461-9301",
    arquivoGPX: "13.gpx",
    nucleoId: 7,
    turno: "VESPERTINO",
},
{
    id: 14,
    nome: "CINTURAO VERDE/FACAO",
    motorista: "EDUARDO DE ALMEIDA CARLINO",
    telefone: "65 99955-9699",
    arquivoGPX: "14.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 15,
    nome: "CINTURAO VERDE/FACAO",
    motorista: "JOSE AUGUSTO DA SILVA CRUZ",
    telefone: "65 999777-5657",
    arquivoGPX: "15.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 16,
    nome: "IPE ROXO/7 LOTES/LARANJEIRA 1",
    motorista: "CLAUDINEI ANACLETO DA SILVA",
    telefone: "65 9801-4528",
    arquivoGPX: "16.gpx",
    nucleoId: 4,
    turno: "MATUTINO",
},
{
    id: 17,
    nome: "IPE ROXO/7 LOTES/LARANJEIRA 1",
    motorista: "CLAUDINEI ANACLETO DA SILVA",
    telefone: "65 9801-4528",
    arquivoGPX: "17.gpx",
    nucleoId: 4,
    turno: "VESPERTINO",
},
{
    id: 18,
    nome: "CORIXA",
    motorista: "AIRTON LOURENCO SALVIANI",
    telefone: "65 9674-1986",
    arquivoGPX: "18.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 19,
    nome: "CORIXINHA/SAPIQUA",
    motorista: "RENATO ANTONIO VIANA",
    telefone: "65 9962-9113",
    arquivoGPX: "19.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 20,
    nome: "AVIAO CAIDO",
    motorista: "DENNIS FABRICIO DA SILVA FERRON",
    telefone: "65 9600-9031",
    arquivoGPX: "20.gpx",
    nucleoId: 12,
    turno: "MATUTINO",
},
{
    id: 21,
    nome: "SANGRADOURO/VALE VERDE/BOQUEIRAO",
    motorista: "DIVANEI UNIMOTO DA CRUZ",
    telefone: "65 9680-8617",
    arquivoGPX: "21.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 22,
    nome: "SANGRADOURO/VALE VERDE/BOQUEIRAO",
    motorista: "DIVANEI UNIMOTO DA CRUZ",
    telefone: "65 9680-8617",
    arquivoGPX: "22.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
{
    id: 23,
    nome: "DOIS DE OURO/AFFEMAT",
    motorista: "LUIZ ORLEI AGUIAR",
    telefone: "65 99964-9434",
    arquivoGPX: "23.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 24,
    nome: "MARGARIDA ALVES/BOA ESPERANCA",
    motorista: "EDER FERREIRA",
    telefone: "65 9911-0415",
    arquivoGPX: "24.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 25,
    nome: "ARIZONA/BOA SORTE/CARANDA",
    motorista: "EDER PRADO DE SOUZA",
    telefone: "65 9607-9876",
    arquivoGPX: "25.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 26,
    nome: "ARIZONA/BOA SORTE/CARANDA",
    motorista: "EDER PRADO DE SOUZA",
    telefone: "65 9607-9876",
    arquivoGPX: "26.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
{
    id: 27,
    nome: "ITIQUIRA/CARAMUJO/SALVACAO",
    motorista: "EDILSON DA CRUZ",
    telefone: "65 9900-9996",
    arquivoGPX: "27.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 28,
    nome: "FLOR DA MATA",
    motorista: "EDISON EGUES",
    telefone: "65 9642-7778",
    arquivoGPX: "28.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 29,
    nome: "BR/PAIOL",
    motorista: "ELTON DOS SANTOS",
    telefone: "65 8453-1069",
    arquivoGPX: "29.gpx",
    nucleoId: 7,
    turno: "MATUTINO",
},
{
    id: 30,
    nome: "BR/PAIOL",
    motorista: "ELTON DOS SANTOS",
    telefone: "65 8453-1069",
    arquivoGPX: "30.gpx",
    nucleoId: 7,
    turno: "VESPERTINO",
},
{
    id: 31,
    nome: "ENCANTO/IPANEMA",
    motorista: "NATANAEL ALVES DA SILVA",
    telefone: "65 99936-2463",
    arquivoGPX: "31.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 32,
    nome: "FAZENDA BAU",
    motorista: "SEBASTIAO RAMOS OLIVEIRA",
    telefone: "65 99914-7203",
    arquivoGPX: "32.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 33,
    nome: "VALE AZUL/TEXEIRINHA",
    motorista: "FRANCISLAINE DOS SANTOS",
    telefone: "65 9956-1461",
    arquivoGPX: "33.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 34,
    nome: "VALE AZUL/TEXEIRINHA",
    motorista: "FRANCISLAINE DOS SANTOS",
    telefone: "65 9956-1461",
    arquivoGPX: "34.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
{
    id: 35,
    nome: "RIO CACHOEIRA/PINDAIVAL",
    motorista: "GONCALO DA COSTA VILANOVA",
    telefone: "65 9996-4238",
    arquivoGPX: "35.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 36,
    nome: "LINHAO DAS BRANCAS",
    motorista: "HENRIQUE RODRGUES LARANJEIRA",
    telefone: "65 9957-6772",
    arquivoGPX: "36.gpx",
    nucleoId: 7,
    turno: "MATUTINO",
},
{
    id: 37,
    nome: "LINHAO DAS BRANCAS",
    motorista: "HENRIQUE RODRGUES LARANJEIRA",
    telefone: "65 9957-6772",
    arquivoGPX: "37.gpx",
    nucleoId: 7,
    turno: "VESPERTINO",
},
{
    id: 38,
    nome: "CAMPARINO/PORTO",
    motorista: "JACKSON FORNAZARI DO NASCIMENTO",
    telefone: "65 9672-9185",
    arquivoGPX: "/gpx/38-LINHAO 1 E 4 ESQUERDO 1.gpx",
    nucleoId: 12,
    turno: "MATUTINO",
},
{
    id: 39,
    nome: "JARDIM AEROPORTO",
    motorista: "RONY OLIVEIRA QUEROZ",
    telefone: "65 99802-4770",
    arquivoGPX: "/gpx/39-LINHAO 1 E 4 ESQUERDO 2.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 40,
    nome: "JARDIM AEROPORTO",
    motorista: "RONY OLIVEIRA QUEROZ",
    telefone: "65 99802-4770",
    arquivoGPX: "/gpx/40-LINHAO DAS BRANCAS 1.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 41,
    nome: "SEPUTUBA/PANAMBI/ARACATUBA",
    motorista: "JERSON MENDES DE CARVALHO",
    telefone: "65 9844-4160",
    arquivoGPX: "/gpx/41-LINHAO DAS BRANCAS 2.gpx",
    nucleoId: 12,
    turno: "MATUTINO",
},
{
    id: 42,
    nome: "FAZENDA OURO VERDE/ZE DO OLEO",
    motorista: "JESUS VALDECI FRANCO RODRIGUES",
    telefone: "65 9941-7125",
    arquivoGPX: "/gpx/42-MARGARIDA ALVES - BOA ESPERANCA.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 43,
    nome: "SEPUTUBINHA/BARRANQUINHO",
    motorista: "JOAO FELIPE DA MATA",
    telefone: "65 9935-7420",
    arquivoGPX: "/gpx/43-MONJOLO - LAGOA - RESERVA 1.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 44,
    nome: "SOJA",
    motorista: "JOEL CAVALCANTI DE ALMEIDA",
    telefone: "65 9948-5799",
    arquivoGPX: "/gpx/44-MONJOLO - LAGOA - RESERVA 2.gpx",
    nucleoId: 8,
    turno: "MATUTINO",
},
{
    id: 45,
    nome: "NOVA LIMEIRA/CACIMBA",
    motorista: "JOSE ANTONIO EVANGELISTA",
    telefone: "65 9999-9303",
    arquivoGPX: "/gpx/45-MT 343 - GUARANDI.gpx",
    nucleoId: 3,
    turno: "MATUTINO",
},
{
    id: 46,
    nome: "NOVA LIMEIRA/CACIMBA",
    motorista: "JOSE ANTONIO EVANGELISTA",
    telefone: "65 9999-9303",
    arquivoGPX: "/gpx/46-NOVA LIMEIRA - CACIMBA 1.gpx",
    nucleoId: 3,
    turno: "VESPERTINO",
},
{
    id: 47,
    nome: "LARANJEIRA/FEIJAO/VIDA NOVA",
    motorista: "JOSE ROBERTO DE MIRANDA",
    telefone: "65 9685-0924",
    arquivoGPX: "/gpx/47-NOVA LIMEIRA - CACIMBA 2.gpx",
    nucleoId: 4,
    turno: "MATUTINO",
},
{
    id: 48,
    nome: "LARANJEIRA/FEIJAO/VIDA NOVA",
    motorista: "JOSE ROBERTO DE MIRANDA",
    telefone: "65 9685-0924",
    arquivoGPX: "/gpx/48-NOVAS FLECHAS 1.gpx",
    nucleoId: 4,
    turno: "VESPERTINO",
},
{
    id: 49,
    nome: "ALEGRIA 1/AGUA BOA",
    motorista: "JULIANO DA SILVA CRUZ",
    telefone: "65 9936-2135",
    arquivoGPX: "/gpx/49-NOVAS FLECHAS 2.gpx",
    nucleoId: 2,
    turno: "VESPERTINO",
},
{
    id: 50,
    nome: "KATIRA/JATOBA/BOA ESPERANCA",
    motorista: "JOSE LEANDRO NUNES",
    telefone: "65 9801-9996",
    arquivoGPX: "/gpx/50-PADRE INACIO 1.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 51,
    nome: "SANTANA/EXU/SAO NICOLAU",
    motorista: "LORIVALDO DE PAULA DE OLIVEIRA",
    telefone: "65 9800-0488",
    arquivoGPX: "/gpx/51-PADRE INACIO 2.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 52,
    nome: "RIO/FAZFEMA/LIMOEIRO",
    motorista: "LUIZ CARLOS RIBEIRO RAMOS",
    telefone: "65 9916-9491",
    arquivoGPX: "/gpx/52-PANTANAL - ANGICO.gpx",
    nucleoId: 6,
    turno: "MATUTINO",
},
{
    id: 53,
    nome: "RIO/FAZFEMA/LIMOEIRO",
    motorista: "LUIZ CARLOS RIBEIRO RAMOS",
    telefone: "65 9916-9491",
    arquivoGPX: "/gpx/53-PEDREIRA - MATADOURO - CASCALHEIRA.gpx",
    nucleoId: 6,
    turno: "VESPERTINO",
},
{
    id: 54,
    nome: "BAIA BELA",
    motorista: "MARCO ANTONIO DO NASCIMENTO",
    telefone: "65 9960-6859",
    arquivoGPX: "/gpx/54-PIUVAL - BARREIRO - SAO FRANCISCO.gpx",
    nucleoId: 8,
    turno: "MATUTINO",
},
{
    id: 55,
    nome: "PIUVAL/BARREIRO/SAO FRANCISCO",
    motorista: "MARIO CAMPOS DA SILVA",
    telefone: "65 9811-2336",
    arquivoGPX: "/gpx/55-PONTA DO MORRO - BOM TEMPO.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 56,
    nome: "SAO GERALDO/PE DE ANTA/SAO FRANCISCO",
    motorista: "ODILIO PEREIRA DE LIMA",
    telefone: "65 9605-5309",
    arquivoGPX: "/gpx/56-QUATRO BOCAS 1.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 57,
    nome: "PANTANAL/ANGICO",
    motorista: "MARIONEY LOURENCO PATRICIO DA SILVA",
    telefone: "65 9961-1810",
    arquivoGPX: "/gpx/57-QUATRO BOCAS 2.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 58,
    nome: "UNIAO/TRABALHO/LINHAO 235",
    motorista: "PAULO CESAR DA SILVA MACHADO",
    telefone: "65 9942-7381",
    arquivoGPX: "/gpx/58-RANCHO SAPIQUA.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 59,
    nome: "UNIAO/TRABALHO/LINHAO 235",
    motorista: "PAULO CESAR DA SILVA MACHADO",
    telefone: "65 9942-7381",
    arquivoGPX: "/gpx/59-RIO CACHOEIRA - PINDAIVAL.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
{
    id: 60,
    nome: "PEDREIRA/MATADOURO/CASCALHEIRA",
    motorista: "GENILDO DA SILVA",
    telefone: "65 996360-7189",
    arquivoGPX: "/gpx/60-RIO - FAZFEMA - LIMOEIRO 1.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 61,
    nome: "PONTA DO MORRO/BOM TEMPO",
    motorista: "FRANCISCO FERREIRA LIMA FILHO",
    telefone: "65 99969-5040",
    arquivoGPX: "/gpx/61-RIO - FAZFEMA - LIMOEIRO 2.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 62,
    nome: "RANCHO SAPIQUA",
    motorista: "ROBSON FRANCISCO BORGES",
    telefone: "65 9948-7537",
    arquivoGPX: "/gpx/62-ROTA PCD 1.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 63,
    nome: "FAZENDA DREBOR/SANTA MARCIA/LIMOEIRO",
    motorista: "REINALDO TEIXEIRA SILVA",
    telefone: "65 9641-1570",
    arquivoGPX: "/gpx/63-ROTA PCD 2.gpx",
    nucleoId: 6,
    turno: "MATUTINO",
},
{
    id: 64,
    nome: "FAZENDA DREBOR/SANTA MARCIA/LIMOEIRO",
    motorista: "REINALDO TEIXEIRA SILVA",
    telefone: "65 9641-1570",
    arquivoGPX: "/gpx/64-ROTA PNE 1.gpx",
    nucleoId: 6,
    turno: "VESPERTINO",
},
{
    id: 65,
    nome: "MT 343/GUARANDI",
    motorista: "RENATO SEBASTIAO DE SOUZA",
    telefone: "65 9616-4969",
    arquivoGPX: "/gpx/65-ROTA PNE 2.gpx",
    nucleoId: 14,
    turno: "VESPERTINO",
},
{
    id: 66,
    nome: "ENCANTO/CORIXA",
    motorista: "ROMARIO DA SILVA FREIRES",
    telefone: "65 9954-3256",
    arquivoGPX: "/gpx/66-SANGRADOURO - VALE VERDE - BOQUEIRAO 1.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 67,
    nome: "SANTA LUZIA/BARRA NOVA",
    motorista: "RONEI DA SILVA GONCALVES NETO",
    telefone: "65 9325-2392",
    arquivoGPX: "/gpx/67-SANGRADOURO - VALE VERDE - BOQUEIRAO 2.gpx",
    nucleoId: 1,
    turno: "VESPERTINO",
},
{
    id: 68,
    nome: "ROTA DO FORDINHO",
    motorista: "FLAVIO BRASILINO DE CAMPOS",
    telefone: "65 99677-5530",
    arquivoGPX: "/gpx/68-SANTA BARBARA - SANTA CRUZ.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 69,
    nome: "ROTA PCD",
    motorista: "WAGNER RODRIGUES DE SOUZA",
    telefone: "65 99947-4152",
    arquivoGPX: "/gpx/69-SANTA CRUZ - MOEDA - SANTA MARIA.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 70,
    nome: "ROTA PCD",
    motorista: "WAGNER RODRIGUES DE SOUZA",
    telefone: "65 99947-4152",
    arquivoGPX: "/gpx/70-SANTA HELENA - FAZENDA COMETA - ALAMBRADO.gpx",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 71,
    nome: "ROTA PNE",
    motorista: "ODENIR JESUS DE PAULA",
    telefone: "65 99917-2749",
    arquivoGPX: "/gpx/71-SANTA LUZIA - BARRA NOVA.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 72,
    nome: "ROTA PNE",
    motorista: "ODENIR JESUS DE PAULA",
    telefone: "65 99917-2749",
    arquivoGPX: "",
    nucleoId: 13,
    turno: "MATUTINO",
},
{
    id: 73,
    nome: "SANTA BARBARA/SANTA CRUZ",
    motorista: "JOAO RAMOS PIRES",
    telefone: "6599815-3120",
    arquivoGPX: "/gpx/72-SANTA RITA - SANTA MARIA.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 74,
    nome: "SANTA CRUZ/MOEDA/SANTA MARIA",
    motorista: "MANOEL JOSE DA SILVA",
    telefone: "65 99693-6409",
    arquivoGPX: "/gpx/73-SANTANA - EXU - SAO NICOLAU.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 75,
    nome: "SANTA HELENA/FAZENDA COMETA/ALAMBRADO",
    motorista: "JOSE LUIZ TORRES DA CUNHA",
    telefone: "65 65 99639-5618",
    arquivoGPX: "/gpx/74-SANTO ANTONIO DAS LENDAS - BARRANCO VERMELHO.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 76,
    nome: "SANTO ANTONIO DAS LENDAS/BARRANCO VERMELHO",
    motorista: "SIDNEI CEBALHO BARONCIELO",
    telefone: "65 9934407953",
    arquivoGPX: "/gpx/75-SAO GERALDO - PE DE ANTA - SAO FRANCISCO.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 77,
    nome: "PADRE INACIO",
    motorista: "SAVIO DA SILVA CEBALHO",
    telefone: "65 9971-2916",
    arquivoGPX: "/gpx/76-SEPUTUBA - PANAMBI - ARACATUBA.gpx",
    nucleoId: 3,
    turno: "MATUTINO",
},
{
    id: 78,
    nome: "PADRE INACIO",
    motorista: "SAVIO DA SILVA CEBALHO",
    telefone: "65 9971-2916",
    arquivoGPX: "/gpx/77-SEPUTUBINHA - BARRANQUINHO.gpx",
    nucleoId: 3,
    turno: "VESPERTINO",
},
{
    id: 79,
    nome: "QUATRO BOCAS",
    motorista: "SEBASTIAO MARTINS NERES",
    telefone: "659614-0062",
    arquivoGPX: "/gpx/78-SOJA.gpx",
    nucleoId: 3,
    turno: "MATUTINO",
},
{
    id: 80,
    nome: "QUATRO BOCAS",
    motorista: "SEBASTIAO MARTINS NERES",
    telefone: "659614-0062",
    arquivoGPX: "/gpx/79-TAQUARAL - PERAPUTANGA - PONTA DO MORRO.gpx",
    nucleoId: 3,
    turno: "VESPERTINO",
},
{
    id: 81,
    nome: "NOVAS FLECHAS",
    motorista: "SIDNEI ADAO DE CAMPOS",
    telefone: "65 9905-3400",
    arquivoGPX: "/gpx/80-TARUMA - PEDRAS.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 82,
    nome: "NOVAS FLECHAS",
    motorista: "SIDNEI ADAO DE CAMPOS",
    telefone: "65 9905-3400",
    arquivoGPX: "/gpx/81-TREMEDAL - CORIXA.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
{
    id: 83,
    nome: "MONJOLO/LAGOA/RESERVA",
    motorista: "SIVANILDO CIRIACO SANTANA",
    telefone: "65 9678-0791",
    arquivoGPX: "/gpx/82-TRES RIOS.gpx",
    nucleoId: 7,
    turno: "MATUTINO",
},
{
    id: 84,
    nome: "MONJOLO/LAGOA/RESERVA",
    motorista: "SIVANILDO CIRIACO SANTANA",
    telefone: "65 9678-0791",
    arquivoGPX: "/gpx/83-UNIAO - TRABALHO - LINHAO 2,3,5 1.gpx",
    nucleoId: 7,
    turno: "VESPERTINO",
},
{
    id: 85,
    nome: "TAQUARAL/PERAPUTANGA/PONTA DO MORRO",
    motorista: "LAURILEU LUIZ DA SILVA JUNIOR",
    telefone: "65 99665-9133",
    arquivoGPX: "/gpx/84-UNIAO - TRABALHO - LINHAO 2,3,5 2.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 86,
    nome: "TARUMA/PEDRAS",
    motorista: "DOUGLAS CAMARGO",
    telefone: "65 99806-7902",
    arquivoGPX: "/gpx/85-VALE AZUL - TEXEIRINHA 1.gpx",
    nucleoId: 13,
    turno: "VESPERTINO",
},
{
    id: 87,
    nome: "TREMEDAL/CORIXA",
    motorista: "DANIELI LOURENCO SALVIANI",
    telefone: "65 9934-7834",
    arquivoGPX: "/gpx/86-VALE AZUL - TEXEIRINHA 2.gpx",
    nucleoId: 11,
    turno: "MATUTINO",
},
{
    id: 88,
    nome: "TRES RIOS",
    motorista: "RENATO TORRES CUNHA",
    telefone: "65 99643-6868",
    arquivoGPX: "/gpx/87-VALE DO MANGAVAL 1.gpx",
    nucleoId: 5,
    turno: "MATUTINO",
},
{
    id: 89,
    nome: "BARRANQUEIRA 1",
    motorista: "VANDERSON BRITO MIRANDA",
    telefone: "65 9353-8785",
    arquivoGPX: "/gpx/88-Vale do Mangal.gpx",
    nucleoId: 2,
    turno: "VESPERTINO",
},
{
    id: 90,
    nome: "LINHAO 1 E 4 ESQUERDO",
    motorista: "WALLACE MORAES DA SILVA",
    telefone: "65 9618-6881",
    arquivoGPX: "/gpx/89-Vida Nova - Laranjeira - Furnas 1.gpx",
    nucleoId: 10,
    turno: "MATUTINO",
},
{
    id: 91,
    nome: "LINHAO 1 E 4 ESQUERDO",
    motorista: "WALLACE MORAES DA SILVA",
    telefone: "65 9618-6881",
    arquivoGPX: "/gpx/90-Vida Nova - Laranjeira - Furnas 2.gpx",
    nucleoId: 10,
    turno: "VESPERTINO",
},
]
